### ISSUE TITLE
Error:Execution failed for task ':app:compileDebugJavaWithJavac'. > java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V

### ISSUE THREAD

**Issue by adhithyagnair** [gonzalonm/RoomDemo#2]
When running this app it shows this error.

Studio 3.0
Gradle 3.0.1
compileSdkVersion 27

**Comment by gonzalonm** [comment]
Hey @adhithyagnair thanks for your feedback. Could you please test this branch https://github.com/gonzalonm/RoomDemo/tree/api27? I tried to reproduce your error but I could not

**Comment by adhithyagnair** [comment]
Hey @gonzalonm  That was not an issue with the code, My antivirus was blocking java from accessing sqlite, Thanks for your comment. :)

**Comment by gonzalonm** [comment]
Good catch!
